project:
  type: website

website:
  title: "Thinking Slow"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/sheharyar-raza-32310829/
      - icon: twitter
        href: https://twitter.com/razasn
format:
  html:
    theme: simplex
    css: styles.css

editor: visual

